version: '3.8'

services:
  gold-bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped